///************************************************
/// Generated by: LinhDH
/// Date: 24/05/2015 09:30:54
/// Goal: Create User Service Class for DM_DON_VI
///************************************************
/// <summary>
/// Create User Service Class for DM_DON_VI
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_DM_DON_VI : US_Object
	{
		private const string c_TableName = "DM_DON_VI";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public string strMA_DON_VI 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "MA_DON_VI", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["MA_DON_VI"] = value;
			}
		}

		public bool IsMA_DON_VINull() 
		{
			return pm_objDR.IsNull("MA_DON_VI");
		}

		public void SetMA_DON_VINull() {
			pm_objDR["MA_DON_VI"] = System.Convert.DBNull;
		}

		public decimal dcID_DV_CHA 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_DV_CHA", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_DV_CHA"] = value;
			}
		}

		public bool IsID_DV_CHANull()	{
			return pm_objDR.IsNull("ID_DV_CHA");
		}

		public void SetID_DV_CHANull() {
			pm_objDR["ID_DV_CHA"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_DM_DON_VI() 
		{
			pm_objDS = new DS_DM_DON_VI();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_DM_DON_VI(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_DM_DON_VI(decimal i_dbID) 
		{
			pm_objDS = new DS_DM_DON_VI();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion

        #region Additional Functions
        public void load_danh_sach_don_vi(DS_DM_DON_VI op_ds)
        {
            CStoredProc v_cstore = new CStoredProc("pr_DM_DON_VI_load_danh_sach_don_vi");
            v_cstore.fillDataSetByCommand(this, op_ds);
        }
        #endregion
    }
}
