///************************************************
/// Generated by: Anhpt
/// Date: 21/09/2015 05:55:45
/// Goal: Create User Service Class for GD_CUOC_GOI_YEU_CAU
///************************************************
/// <summary>
/// Create User Service Class for GD_CUOC_GOI_YEU_CAU
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using IPCOREDS.CDBNames;


namespace IPCOREUS
{

	public class US_GD_CUOC_GOI_YEU_CAU : US_Object
	{
		private const string c_TableName = "GD_CUOC_GOI_YEU_CAU";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public string strCUOC_GOI_VAO_YN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "CUOC_GOI_VAO_YN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["CUOC_GOI_VAO_YN"] = value;
			}
		}

		public bool IsCUOC_GOI_VAO_YNNull() 
		{
			return pm_objDR.IsNull("CUOC_GOI_VAO_YN");
		}

		public void SetCUOC_GOI_VAO_YNNull() {
			pm_objDR["CUOC_GOI_VAO_YN"] = System.Convert.DBNull;
		}

		public string strCALL_ID 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "CALL_ID", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["CALL_ID"] = value;
			}
		}

		public bool IsCALL_IDNull() 
		{
			return pm_objDR.IsNull("CALL_ID");
		}

		public void SetCALL_IDNull() {
			pm_objDR["CALL_ID"] = System.Convert.DBNull;
		}

		public string strVOICE_CALL_LINK 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "VOICE_CALL_LINK", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["VOICE_CALL_LINK"] = value;
			}
		}

		public bool IsVOICE_CALL_LINKNull() 
		{
			return pm_objDR.IsNull("VOICE_CALL_LINK");
		}

		public void SetVOICE_CALL_LINKNull() {
			pm_objDR["VOICE_CALL_LINK"] = System.Convert.DBNull;
		}

		public DateTime datSTART_TIME
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "START_TIME", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["START_TIME"] = value;
			}
		}

		public bool IsSTART_TIMENull()
		{
			return pm_objDR.IsNull("START_TIME");
		}

		public void SetSTART_TIMENull()
		{
			pm_objDR["START_TIME"] = System.Convert.DBNull;
		}

		public DateTime datEND_TIME
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "END_TIME", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["END_TIME"] = value;
			}
		}

		public bool IsEND_TIMENull()
		{
			return pm_objDR.IsNull("END_TIME");
		}

		public void SetEND_TIMENull()
		{
			pm_objDR["END_TIME"] = System.Convert.DBNull;
		}

		public decimal dcSTATION_ID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "STATION_ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["STATION_ID"] = value;
			}
		}

		public bool IsSTATION_IDNull()	{
			return pm_objDR.IsNull("STATION_ID");
		}

		public void SetSTATION_IDNull() {
			pm_objDR["STATION_ID"] = System.Convert.DBNull;
		}

		public decimal dcDURATION 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "DURATION", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["DURATION"] = value;
			}
		}

		public bool IsDURATIONNull()	{
			return pm_objDR.IsNull("DURATION");
		}

		public void SetDURATIONNull() {
			pm_objDR["DURATION"] = System.Convert.DBNull;
		}

		public string strSTATUS 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "STATUS", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["STATUS"] = value;
			}
		}

		public bool IsSTATUSNull() 
		{
			return pm_objDR.IsNull("STATUS");
		}

		public void SetSTATUSNull() {
			pm_objDR["STATUS"] = System.Convert.DBNull;
		}

		public string strERROR_CODE 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "ERROR_CODE", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["ERROR_CODE"] = value;
			}
		}

		public bool IsERROR_CODENull() 
		{
			return pm_objDR.IsNull("ERROR_CODE");
		}

		public void SetERROR_CODENull() {
			pm_objDR["ERROR_CODE"] = System.Convert.DBNull;
		}

		public string strERROR_DESC 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "ERROR_DESC", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["ERROR_DESC"] = value;
			}
		}

		public bool IsERROR_DESCNull() 
		{
			return pm_objDR.IsNull("ERROR_DESC");
		}

		public void SetERROR_DESCNull() {
			pm_objDR["ERROR_DESC"] = System.Convert.DBNull;
		}

		public DateTime datDATETIME_RESPOND
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "DATETIME_RESPOND", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["DATETIME_RESPOND"] = value;
			}
		}

		public bool IsDATETIME_RESPONDNull()
		{
			return pm_objDR.IsNull("DATETIME_RESPOND");
		}

		public void SetDATETIME_RESPONDNull()
		{
			pm_objDR["DATETIME_RESPOND"] = System.Convert.DBNull;
		}

		public decimal dcRINGTIME 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "RINGTIME", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["RINGTIME"] = value;
			}
		}

		public bool IsRINGTIMENull()	{
			return pm_objDR.IsNull("RINGTIME");
		}

		public void SetRINGTIMENull() {
			pm_objDR["RINGTIME"] = System.Convert.DBNull;
		}

		public DateTime datTHOI_DIEM_GOI
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "THOI_DIEM_GOI", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["THOI_DIEM_GOI"] = value;
			}
		}

		public bool IsTHOI_DIEM_GOINull()
		{
			return pm_objDR.IsNull("THOI_DIEM_GOI");
		}

		public void SetTHOI_DIEM_GOINull()
		{
			pm_objDR["THOI_DIEM_GOI"] = System.Convert.DBNull;
		}

		public decimal dcID_DAT_HANG 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_DAT_HANG", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_DAT_HANG"] = value;
			}
		}

		public bool IsID_DAT_HANGNull()	{
			return pm_objDR.IsNull("ID_DAT_HANG");
		}

		public void SetID_DAT_HANGNull() {
			pm_objDR["ID_DAT_HANG"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_GD_CUOC_GOI_YEU_CAU() 
		{
			pm_objDS = new DS_GD_CUOC_GOI_YEU_CAU();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_GD_CUOC_GOI_YEU_CAU(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_GD_CUOC_GOI_YEU_CAU(decimal i_dbID) 
		{
			pm_objDS = new DS_GD_CUOC_GOI_YEU_CAU();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion

        public bool is_call_id_exist(string ip_str_call_id)
        {
            DS_GD_CUOC_GOI_YEU_CAU v_ds_gd_cuoc_goi_yc = new DS_GD_CUOC_GOI_YEU_CAU();
            this.FillDataset(v_ds_gd_cuoc_goi_yc, " WHERE GD_CUOC_GOI_YEU_CAU.CALL_ID" + " = '" + ip_str_call_id + "'");
            if (v_ds_gd_cuoc_goi_yc.GD_CUOC_GOI_YEU_CAU.Rows.Count > 0) return true;
            return false;
        }

	}
}
