'************************************************
'* Generated by: IPC
'* Date: 18/11/2003
'* Goal: Create User Service Class for CM_DM_LOAI_TD
'************************************************

option Explicit On
option Strict On
Imports IP.Core.IPData
Imports IP.Core.IPBusinessService
Imports IP.Core.IPCommon

Public Class US_CM_DM_LOAI_TD
	Inherits US_Object

	Private Const c_TableName as String = "CM_DM_LOAI_TD"

#Region "Public Property"

	Public Property dcID() As Decimal
		Get
			Return CType(pm_objDR.Item("ID"), Decimal)
		End Get
		Set(ByVal Value As Decimal)
			pm_objDR.Item("ID") = Value
		End Set
	End Property

	Public Property strMA_LOAI() As String
		Get
			Return CType(pm_objDR.Item("MA_LOAI"), String)
		End Get
		Set(ByVal Value As String)
			pm_objDR.Item("MA_LOAI") = Value
		End Set
	End Property

	Public Property strTEN_LOAI() As String
		Get
			Return CType(pm_objDR.Item("TEN_LOAI"), String)
		End Get
		Set(ByVal Value As String)
			pm_objDR.Item("TEN_LOAI") = Value
		End Set
	End Property

#End Region


	Public Sub New()
		pm_objDS = New DS_CM_DM_LOAI_TD()
		pm_strTableName = c_TableName
		pm_objDR = pm_objDS.Tables(pm_strTableName).NewRow()
	End Sub

	Public Sub New(ByVal i_objDR As DataRow)
		Me.New()
		Me.DataRow2Me(i_objDR)
	End Sub

	Public Sub New(ByVal i_dbID As Decimal)
		pm_objDS = New DS_CM_DM_LOAI_TD()
		pm_strTableName = c_TableName
        Me.FillDataset(pm_objDS, "Where ID = " & Str(i_dbID))
		pm_objDR = getRowClone(pm_objds.Tables(pm_strTableName).Rows(0))
	End Sub

    Public Sub New(ByVal i_strMaLoaiTD As String)
        pm_objDS = New DS_CM_DM_LOAI_TD()
        pm_strTableName = c_TableName

        Dim v_cmd As SqlClient.SqlCommand
        Dim v_MakeSelCommand As IMakeSelectCmd
        v_MakeSelCommand = New CMakeAndSelectCmd(pm_objDS, c_TableName)
        v_MakeSelCommand.AddCondition("MA_LOAI", i_strMaLoaiTD, eKieuDuLieu.KieuString, eKieuSoSanh.Bang)
        v_cmd = v_MakeSelCommand.getSelectCmd()

        Me.FillDatasetByCommand(pm_objDS, v_cmd)
        pm_objDR = getRowClone(pm_objds.Tables(pm_strTableName).Rows(0))
    End Sub


#Region "Inner class"
    Public Class MA_LOAI_TU_DIEN
        Public Const THANH_PHO_TINH As String = "TP" 'Thành phố - tỉnh
        Public Const CAP_QUAN_LY As String = "CQL" 'Cấp quản lý 
        Public Const LOAI_TRUONG As String = "HTSH" 'Lọai trường
        Public Const LOAI_PHAN_QUYEN As String = "LPQ" 'Loại phân quyền
        Public Const LOAI_THAM_SO As String = "LTS" 'Lọai tham số 
        Public Const GIOI_TINH As String = "GT" 'Giới tính
        Public Const TON_GIAO As String = "TOG" 'Tôn giáo
        Public Const DAN_TOC As String = "DT" 'Dân tộc
        Public Const LOAI_DIEM As String = "LOAI_DIEM" 'Loại điểm của bài thi và kiểm tra
        Public Const TRANG_THAI_NAM_KH As String = "TT_NAM_KH" 'Trạng thái năm kế hoạch
        Public Const TRANG_THAI_HK_KH As String = "TT_HK_KH" 'Trạng thái học kỳ kế hoạch
        Public Const LOAI_DIEM_LT_HAY_TH As String = "LT_HAY_TH" 'Loại điểm lý thuyết hay thực hành
        Public Const KHU_VUC_TUYEN_SINH As String = "KVTS" 'Khu vực tuyển sinh
        Public Const DOI_TUONG_TUYEN_SINH As String = "DTTS" 'Đối tượng tuyển sinh
        Public Const THANG_QUY_NAM As String = "TQN" 'Tháng,Quý,Năm
        Public Const TRANG_THAI_SINH_VIEN As String = "TTSV" 'Trạng thái sinh viên
        Public Const MA_LOAI_VAN_BANG As String = "MLVB" 'Mã loại văn bằng

    End Class
#End Region

End Class
