//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPCOREDS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINHDH-PC\\SQLEXPRESS;Initial Catalog=TCM;Persist Security Info=True;U" +
            "ser ID=sa;Password=sa")]
        public string TCMConnectionString {
            get {
                return ((string)(this["TCMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DAOVIETHIEN-PC;Initial Catalog=CRM.HN_03;Persist Security Info=True;U" +
            "ser ID=sa;Password=sa")]
        public string CRM_HN_03ConnectionString {
            get {
                return ((string)(this["CRM_HN_03ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINHDH-PC\\SQLEXPRESS;Initial Catalog=CRM.HN_03;Persist Security Info=" +
            "True;User ID=sa;Password=sa")]
        public string CRM_HN_03ConnectionString1 {
            get {
                return ((string)(this["CRM_HN_03ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.5;Initial Catalog=TOS_TicketSystem;Persist Security Info=T" +
            "rue;User ID=crmtpe;Password=crmtpe@topica#2014")]
        public string TOS_TicketSystemConnectionString {
            get {
                return ((string)(this["TOS_TicketSystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.5;Initial Catalog=TOS_TicketSystem;User ID=crmtpe;Password" +
            "=crmtpe@topica#2014")]
        public string TOS_TicketSystemConnectionString1 {
            get {
                return ((string)(this["TOS_TicketSystemConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.121.74;Initial Catalog=TOS_TicketSystem;Persist Security Info" +
            "=True;User ID=crmtpe;Password=crmtpe@topica#2014")]
        public string TOS_TicketSystemConnectionString2 {
            get {
                return ((string)(this["TOS_TicketSystemConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINHDH-PC\\SQLEXPRESS;Initial Catalog=DVMC;Persist Security Info=True;" +
            "User ID=sa;Password=sa")]
        public string DVMCConnectionString {
            get {
                return ((string)(this["DVMCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=42.112.28.4;Initial Catalog=DVMC;User ID=sa;Password=admin@topica#14")]
        public string DVMCConnectionString1 {
            get {
                return ((string)(this["DVMCConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=anhpt-pc\\sqlexpressr2;Initial Catalog=DVMC;Persist Security Info=True" +
            ";User ID=sa;Password=sa123456")]
        public string DVMCConnectionString2 {
            get {
                return ((string)(this["DVMCConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=27.118.16.97;Initial Catalog=BKI_DVMC;Persist Security Info=True;User" +
            " ID=sa;Password=123@bcdE.!@#_ATT")]
        public string BKI_DVMCConnectionString {
            get {
                return ((string)(this["BKI_DVMCConnectionString"]));
            }
        }
    }
}
